[build]
jobs = 1

[profile.dev]
incremental = false

[profile.release]
incremental = false
codegen-units = 1
lto = "off"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
